services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - '8000:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  php:
    build:
      context: ./dockerfile
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    user: ${UID}:${GID}
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  composer:
    build:
      context: ./dockerfile
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
    user: ${UID}:${GID}
#  artisan: