services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - '8000:80'
    depends_on:
      - app
      - mysql
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  app:
    container_name: app
    build:
      context: ./dockerfile
      dockerfile: app.dockerfile
    volumes:
      - ./src:/var/www/html
    user: ${UID}:${GID}
